webtalk_init -webtalk_dir E:/_Vivado/MIPS_CPU_Design/MultiCycleCPU/MultiCycleCPU.sim/sim_1/behav/xsim/xsim.dir/Basys3_sim_1_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Dec 18 20:27:24 2018" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2188600" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "07538fbbc1605e9c94f1cca33d9a8606" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "f004e947a4f44df5943d9f668432b736" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "20" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2808 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "8 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "3" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.38_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "11448_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1269097875 -regid "" -xml E:/_Vivado/MIPS_CPU_Design/MultiCycleCPU/MultiCycleCPU.sim/sim_1/behav/xsim/xsim.dir/Basys3_sim_1_behav/webtalk/usage_statistics_ext_xsim.xml -html E:/_Vivado/MIPS_CPU_Design/MultiCycleCPU/MultiCycleCPU.sim/sim_1/behav/xsim/xsim.dir/Basys3_sim_1_behav/webtalk/usage_statistics_ext_xsim.html -wdm E:/_Vivado/MIPS_CPU_Design/MultiCycleCPU/MultiCycleCPU.sim/sim_1/behav/xsim/xsim.dir/Basys3_sim_1_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
