set_property IOSTANDARD LVCMOS33 [get_ports clock]
set_property IOSTANDARD LVCMOS33 [get_ports reset]


set_property IOSTANDARD LVCMOS33 [get_ports {dispcode[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dispcode[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dispcode[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dispcode[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dispcode[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dispcode[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dispcode[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dispcode[0]}]


set_property PACKAGE_PIN W5 [get_ports clock]
set_property PACKAGE_PIN T17 [get_ports reset]


set_property PACKAGE_PIN V7 [get_ports {dispcode[7]}]
set_property PACKAGE_PIN U7 [get_ports {dispcode[6]}]
set_property PACKAGE_PIN V5 [get_ports {dispcode[5]}]
set_property PACKAGE_PIN U5 [get_ports {dispcode[4]}]
set_property PACKAGE_PIN V8 [get_ports {dispcode[3]}]
set_property PACKAGE_PIN U8 [get_ports {dispcode[2]}]
set_property PACKAGE_PIN W6 [get_ports {dispcode[1]}]
set_property PACKAGE_PIN W7 [get_ports {dispcode[0]}]




set_property IOSTANDARD LVCMOS33 [get_ports {hex0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hex0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hex0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hex0[0]}]
set_property PACKAGE_PIN W17 [get_ports {hex0[3]}]
set_property PACKAGE_PIN W16 [get_ports {hex0[2]}]
set_property PACKAGE_PIN V16 [get_ports {hex0[1]}]
set_property PACKAGE_PIN V17 [get_ports {hex0[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {enable[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {enable[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {enable[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {enable[0]}]
set_property PACKAGE_PIN W4 [get_ports {enable[3]}]
set_property PACKAGE_PIN V4 [get_ports {enable[2]}]
set_property PACKAGE_PIN U4 [get_ports {enable[1]}]
set_property PACKAGE_PIN U2 [get_ports {enable[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports light]
set_property PACKAGE_PIN E19 [get_ports light]

set_property IOSTANDARD LVCMOS33 [get_ports {hex1[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hex1[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hex1[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hex1[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hex3[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hex3[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hex3[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hex3[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hex2[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hex2[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hex2[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hex2[0]}]
set_property PACKAGE_PIN R2 [get_ports {hex3[3]}]
set_property PACKAGE_PIN T1 [get_ports {hex3[2]}]
set_property PACKAGE_PIN U1 [get_ports {hex3[1]}]
set_property PACKAGE_PIN W2 [get_ports {hex3[0]}]
set_property PACKAGE_PIN R3 [get_ports {hex2[3]}]
set_property PACKAGE_PIN T2 [get_ports {hex2[2]}]
set_property PACKAGE_PIN T3 [get_ports {hex2[1]}]
set_property PACKAGE_PIN V2 [get_ports {hex2[0]}]
set_property PACKAGE_PIN W13 [get_ports {hex1[3]}]
set_property PACKAGE_PIN W14 [get_ports {hex1[2]}]
set_property PACKAGE_PIN V15 [get_ports {hex1[1]}]
set_property PACKAGE_PIN W15 [get_ports {hex1[0]}]
