# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/_Vivado/MIPS_CPU_Design/SingleCycleCPU/SingleCycleCPU.cache/wt [current_project]
set_property parent.project_path E:/_Vivado/MIPS_CPU_Design/SingleCycleCPU/SingleCycleCPU.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo e:/_Vivado/MIPS_CPU_Design/SingleCycleCPU/SingleCycleCPU.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  E:/_Vivado/MIPS_CPU_Design/SingleCycleCPU/SingleCycleCPU.srcs/sources_1/new/ALU.v
  E:/_Vivado/MIPS_CPU_Design/SingleCycleCPU/SingleCycleCPU.srcs/sources_1/new/ControlUnit.v
  E:/_Vivado/MIPS_CPU_Design/SingleCycleCPU/SingleCycleCPU.srcs/sources_1/new/DataMemory.v
  E:/_Vivado/MIPS_CPU_Design/SingleCycleCPU/SingleCycleCPU.srcs/sources_1/new/ImmediateExtend.v
  E:/_Vivado/MIPS_CPU_Design/SingleCycleCPU/SingleCycleCPU.srcs/sources_1/new/InstructionMemory.v
  E:/_Vivado/MIPS_CPU_Design/SingleCycleCPU/SingleCycleCPU.srcs/sources_1/new/Mux2_5bits.v
  E:/_Vivado/MIPS_CPU_Design/SingleCycleCPU/SingleCycleCPU.srcs/sources_1/new/Mux4_32bits.v
  E:/_Vivado/MIPS_CPU_Design/SingleCycleCPU/SingleCycleCPU.srcs/sources_1/new/PC.v
  E:/_Vivado/MIPS_CPU_Design/SingleCycleCPU/SingleCycleCPU.srcs/sources_1/new/RegisterFile.v
  E:/_Vivado/MIPS_CPU_Design/SingleCycleCPU/SingleCycleCPU.srcs/sources_1/new/Mux2_32bits.v
  E:/_Vivado/MIPS_CPU_Design/SingleCycleCPU/SingleCycleCPU.srcs/sources_1/new/top_CPU.v
  E:/_Vivado/MIPS_CPU_Design/SingleCycleCPU/SingleCycleCPU.srcs/sources_1/new/clk_div.v
  E:/_Vivado/MIPS_CPU_Design/SingleCycleCPU/SingleCycleCPU.srcs/sources_1/new/Counter4.v
  E:/_Vivado/MIPS_CPU_Design/SingleCycleCPU/SingleCycleCPU.srcs/sources_1/new/Hex_To_7Seg.v
  E:/_Vivado/MIPS_CPU_Design/SingleCycleCPU/SingleCycleCPU.srcs/sources_1/new/Mux4_4bits.v
  E:/_Vivado/MIPS_CPU_Design/SingleCycleCPU/SingleCycleCPU.srcs/sources_1/new/Four_LED.v
  E:/_Vivado/MIPS_CPU_Design/SingleCycleCPU/SingleCycleCPU.srcs/sources_1/new/Basys3_CPU.v
  E:/_Vivado/MIPS_CPU_Design/SingleCycleCPU/SingleCycleCPU.srcs/sources_1/new/Button_Debounce.v
  E:/_Vivado/MIPS_CPU_Design/SingleCycleCPU/SingleCycleCPU.srcs/sources_1/new/Mux4_16bits.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/_Vivado/MIPS_CPU_Design/SingleCycleCPU/SingleCycleCPU.srcs/constrs_1/new/Basys3_CPU_1.xdc
set_property used_in_implementation false [get_files E:/_Vivado/MIPS_CPU_Design/SingleCycleCPU/SingleCycleCPU.srcs/constrs_1/new/Basys3_CPU_1.xdc]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top Basys3_CPU -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Basys3_CPU.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Basys3_CPU_utilization_synth.rpt -pb Basys3_CPU_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
